export const recentUploads = [
	{
		id: 1,
		image: "/assets/uploads/child1.svg",
		name: "Rita Moses",
		missingDate: "04/07/2023",
		age: "4 years",
		gender: "female",
	},
	{
		id: 2,
		image: "/assets/uploads/child2.svg",
		name: "Rita Moses",
		missingDate: "04/07/2023",
		age: "4 years",
		gender: "female",
	},
	{
		id: 3,
		image: "/assets/uploads/child3.svg",
		name: "Rita Moses",
		missingDate: "04/07/2023",
		age: "4 years",
		gender: "female",
	},
	{
		id: 4,
		image: "/assets/uploads/child4.svg",
		name: "Rita Moses",
		missingDate: "04/07/2023",
		age: "4 years",
		gender: "female",
	},
	{
		id: 5,
		image: "/assets/uploads/child5.svg",
		name: "Rita Moses",
		missingDate: "04/07/2023",
		age: "4 years",
		gender: "female",
	},
	{
		id: 6,
		image: "/assets/uploads/child6.svg",
		name: "Rita Moses",
		missingDate: "04/07/2023",
		age: "4 years",
		gender: "female",
	},
	{
		id: 7,
		image: "/assets/uploads/child1.svg",
		name: "Rita Moses",
		missingDate: "04/07/2023",
		age: "4 years",
		gender: "female",
	},
	{
		id: 8,
		image: "/assets/uploads/child2.svg",
		name: "Rita Moses",
		missingDate: "04/07/2023",
		age: "4 years",
		gender: "female",
	},
];
